drop table if exists author;
drop table if exists book;
drop table if exists book_author;
drop table if exists book_category;
drop table if exists category;
drop table if exists order_item;
drop table if exists orders;
drop table if exists role;
drop table if exists user;
create table author (author_id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (author_id)) engine=InnoDB;
create table book (book_id bigint not null auto_increment, amount integer not null, is_deleted bit not null, name varchar(255), price double precision not null, primary key (book_id)) engine=InnoDB;
create table book_author (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id)) engine=InnoDB;
create table book_category (book_id bigint not null, category_id bigint not null, primary key (book_id, category_id)) engine=InnoDB;
create table category (category_id bigint not null auto_increment, is_deleted bit not null, name varchar(255), primary key (category_id)) engine=InnoDB;
create table order_item (order_item_id bigint not null auto_increment, amount integer not null, book_id bigint, order_id bigint, primary key (order_item_id)) engine=InnoDB;
create table orders (order_id bigint not null auto_increment, order_date datetime, total double precision not null, user_id bigint, primary key (order_id)) engine=InnoDB;
create table role (role_id bigint not null, name varchar(255), primary key (role_id)) engine=InnoDB;
create table user (user_id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), username varchar(255), role_id bigint, primary key (user_id)) engine=InnoDB;
alter table book_author add constraint FKbjqhp85wjv8vpr0beygh6jsgo foreign key (author_id) references author (author_id);
alter table book_author add constraint FKhwgu59n9o80xv75plf9ggj7xn foreign key (book_id) references book (book_id);
alter table book_category add constraint FKam8llderp40mvbbwceqpu6l2s foreign key (category_id) references category (category_id);
alter table book_category add constraint FKnyegcbpvce2mnmg26h0i856fd foreign key (book_id) references book (book_id);
alter table order_item add constraint FKb033an1f8qmpbnfl0a6jb5njs foreign key (book_id) references book (book_id);
alter table order_item add constraint FKt4dc2r9nbvbujrljv3e23iibt foreign key (order_id) references orders (order_id);
alter table orders add constraint FKel9kyl84ego2otj2accfd8mr7 foreign key (user_id) references user (user_id);
alter table user add constraint FKn82ha3ccdebhokx3a8fgdqeyy foreign key (role_id) references role (role_id);