drop table if exists author cascade;
drop table if exists book cascade;
drop table if exists book_author cascade;
drop table if exists book_category cascade;
drop table if exists category cascade;
drop table if exists order_item cascade;
drop table if exists orders cascade;
drop table if exists roles cascade;
drop table if exists users cascade;
create table author (author_id  bigserial not null, first_name varchar(255), last_name varchar(255), primary key (author_id));
create table book (book_id  bigserial not null, amount int4 not null, is_deleted boolean not null, title varchar(255), price float8 not null, primary key (book_id));
create table book_author (book_id int8 not null, author_id int8 not null, primary key (book_id, author_id));
create table book_category (book_id int8 not null, category_id int8 not null, primary key (book_id, category_id));
create table category (category_id  bigserial not null, is_deleted boolean not null, name varchar(255), primary key (category_id));
create table order_item (order_item_id  bigserial not null, amount int4 not null, book_id int8, order_id int8, primary key (order_item_id));
create table orders (order_id  bigserial not null, order_date timestamp, total float8 not null, user_id int8, primary key (order_id));
create table roles (role_id int8 not null, name varchar(255), primary key (role_id));
create table users (user_id  bigserial not null, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), username varchar(255), role_id int8, primary key (user_id));
alter table book_author add constraint FKbjqhp85wjv8vpr0beygh6jsgo foreign key (author_id) references author;
alter table book_author add constraint FKhwgu59n9o80xv75plf9ggj7xn foreign key (book_id) references book;
alter table book_category add constraint FKam8llderp40mvbbwceqpu6l2s foreign key (category_id) references category;
alter table book_category add constraint FKnyegcbpvce2mnmg26h0i856fd foreign key (book_id) references book;
alter table order_item add constraint FKb033an1f8qmpbnfl0a6jb5njs foreign key (book_id) references book;
alter table order_item add constraint FKt4dc2r9nbvbujrljv3e23iibt foreign key (order_id) references orders;
alter table orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table users add constraint FK4qu1gr772nnf6ve5af002rwya foreign key (role_id) references roles;
